### ISSUE TITLE
create release 3.2.0

### ISSUE THREAD

**Issue by orbeckst** [jensengroup/propka#66]
First official release will be 3.2.0

- [x] Update repo URL in documentation
- [x] Merge PR #61 
- [x] Change repo name
- [x] release files on GitHub
- [x] PyPi package

See PR #61 .

**Comment by sobolevnrm** [comment]
`pip install propka`

Yay!

**Comment by orbeckst** [comment]
Works on macOS.

Thank you so much, this is awesome.

Do you have any channels to distribute the good news?

**Comment by orbeckst** [comment]
P.S.: I did
```
pip install --upgrade propka
```

**Comment by sobolevnrm** [comment]
> Works on macOS.
> 
> Thank you so much, this is awesome.
> 
> Do you have any channels to distribute the good news?

It's a good question.  I could post to Twitter and LinkedIn but I don't want to steal @jhjensen2 's thunder.

**Comment by jhjensen2** [comment]
No thunder to steal. Post as much as you like

**Comment by sobolevnrm** [comment]
I tweeted the announcement https://twitter.com/nathanabaker/status/1274343442735226880 and posted to LinkedIn https://www.linkedin.com/posts/nathanandrewbaker_jensengrouppropka-activity-6680109470082842624-LXUi.  I'm hesitant to post to the APBS mailing list because the new version isn't yet integrated into PDB2PQR (@kozlac and @intendo are working on this).  

Who wants to make the Tik Tok video announcing the release? :)
