### ISSUE TITLE
enable codecov as a PR check

### ISSUE THREAD

**Issue by orbeckst** [jensengroup/propka#77]
With #71 (and #76) we should get a sense for coverage. This should be included as one of the PR checks.

**Comment by orbeckst** [comment]
[Quick Start](https://docs.codecov.io/docs/quick-start) says: A repo admin should install the [codecov Github Marketplace app](https://github.com/marketplace/codecov) (which is probably the same as https://github.com/apps/codecov ).

**Comment by orbeckst** [comment]
I tried to configure it for jensengroup/propka and it offered me a "request access" button – maybe @sobolevnrm will have to do it or confirm.

**Comment by sobolevnrm** [comment]
@orbeckst I've given you access.  However, I can't get the QuickStart instructions to work since it appears to look at organizations I control rather than specific repositories where I am an admin.  We could reactivate the Electrostatics/propka fork of the jensengroup/propka repo but that seems like a sub-optimal solution.  What do you suggest?

**Comment by sobolevnrm** [comment]
Maybe I'm wrong; it looks like this works:  https://codecov.io/github/jensengroup/propka

**Comment by sobolevnrm** [comment]
@orbeckst - does this resolve the issue?

**Comment by orbeckst** [comment]
All works, sorry, only saw this right now.
